# -*- coding: utf-8 -*-
"""bert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dtlc_qUsyy1lAm6hiAMqSrV4TJXKbVC8
"""

import transformers
from transformers import BertTokenizer,BertForQuestionAnswering,BertConfig
import torch

def bert(question_user,answer_user):

  tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
  model_s = BertForQuestionAnswering.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')
  question = question_user
  context = answer_user
  input_id = tokenizer.encode(question,context)
  tokens = tokenizer.convert_ids_to_tokens(input_id)


  seg_index = input_id.index(tokenizer.sep_token_id)
  num_seg_a = seg_index + 1
  num_seg_b = len(input_id) - num_seg_a
  segment_ids = [0]*num_seg_a + [1]*num_seg_b

  assert len(segment_ids) == len(input_id)
  start_score, end_score = model_s(torch.tensor([input_id]),token_type_ids=torch.tensor([segment_ids]),return_dict=False)
  starts = torch.argmax(start_score)
  ends = torch.argmax(end_score)
  answer = ' '.join(tokens[starts:ends+1])

  answer = tokens[starts]

  for i in range(starts + 1, ends + 1):
    if tokens[i][0:2] == '##':
        answer += tokens[i][2:]
    else:
        answer += ' ' + tokens[i]

  return answer

#bert('Who am I?','I am Rukmini friend of uday.')